// <auto-generated />
namespace MoviesOnLine.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class movie_created : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(movie_created));
        
        string IMigrationMetadata.Id
        {
            get { return "201910171606160_movie_created"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
